#!/bin/bash
# Author: Surya-Raghuram [GitHub: Surya-Raghuram]

echo "Created by Surya-Raghuram [GitHub: Surya-Raghuram]"
echo ""
echo "This is for IIITA campus proxy only, allows you to set your own Username and Password, and uses 8080 as Port number"

# don't let script run as root
if (( $EUID == 0 )); then
    echo -e "\n\nPlease DON'T run as root!\n"
    exit
fi

read -p "Please enter the proxy host you want to apply (eg, 172.31.2.4) : " proxy
echo ""

read -p "Please enter your proxy username: " proxy_username
read -s -p "Please enter your proxy password: " proxy_password
echo ""  

echo "Setting up $proxy with Username: $proxy_username"

###############################################################################
# Removing old proxy configs
###############################################################################

echo "Removing proxies from environment variables"
sudo sed -i '/http_proxy/d' /etc/environment
sudo sed -i '/https_proxy/d' /etc/environment
sudo sed -i '/ftp_proxy/d' /etc/environment
sudo sed -i '/socks_proxy/d' /etc/environment
sudo sed -i '/all_proxy/d' /etc/environment
sudo sed -i '/HTTP_PROXY/d' /etc/environment
sudo sed -i '/HTTPS_PROXY/d' /etc/environment
sudo sed -i '/FTP_PROXY/d' /etc/environment
sudo sed -i '/SOCKS_PROXY/d' /etc/environment
sudo sed -i '/ALL_PROXY/d' /etc/environment
sudo perl -i -pe 'chomp if eof' /etc/environment
echo "done."

echo "Removing proxies from pacman"
sudo sed -i '/XferCommand/d' /etc/pacman.conf
sudo sed -i '/ProxyServer/d' /etc/pacman.conf
sudo perl -i -pe 'chomp if eof' /etc/pacman.conf
echo "done."

echo "Removing proxies from yay"
sed -i '/proxy/d' ~/.config/yay/config.json 2>/dev/null || true
echo "done."

###############################################################################
# Adding new proxy configs
###############################################################################

echo "Adding proxies to environment variables"
sudo perl -i -pe 'chomp if eof' /etc/environment
sudo sh -c "echo '\nhttp_proxy=http://$proxy_username:$proxy_password@$proxy:8080/\nhttps_proxy=http://$proxy_username:$proxy_password@$proxy:8080/\nftp_proxy=http://$proxy_username:$proxy_password@$proxy:8080/\n' >> /etc/environment"
sudo sh -c "echo '\nHTTP_PROXY=http://$proxy_username:$proxy_password@$proxy:8080/\nHTTPS_PROXY=http://$proxy_username:$proxy_password@$proxy:8080/\nFTP_PROXY=http://$proxy_username:$proxy_password@$proxy:8080/\n' >> /etc/environment"
echo "done."

echo "Adding proxies to pacman"
sudo sh -c "echo 'XferCommand = /usr/bin/curl --proxy http://$proxy_username:$proxy_password@$proxy:8080/ -L -C - -f %u > %o' >> /etc/pacman.conf"
echo "done."

echo "Adding proxies to yay"
mkdir -p ~/.config/yay
cat > ~/.config/yay/config.json <<EOF
{
  "proxy": "http://$proxy_username:$proxy_password@$proxy:8080/"
}
EOF
echo "done."

###############################################################################
# Applying proxies to other tools
###############################################################################

echo "Applying proxies to snap"
sudo snap set system proxy.http=http://$proxy_username:$proxy_password@$proxy:8080/
sudo snap set system proxy.https=http://$proxy_username:$proxy_password@$proxy:8080/
echo "done."

echo "Applying proxy settings to git"
git config --global http.proxy http://$proxy_username:$proxy_password@$proxy:8080
git config --global https.proxy http://$proxy_username:$proxy_password@$proxy:8080
echo "done."

echo "Applying proxy settings to npm"
npm config set proxy http://$proxy_username:$proxy_password@$proxy:8080
npm config set https-proxy http://$proxy_username:$proxy_password@$proxy:8080
echo "done."

###############################################################################
# Finish
###############################################################################

echo ""
echo "All done! $proxy with username $proxy_username successfully applied."
echo "If connectivity problems persist, log out/in or reboot."
