#!/bin/bash
# Author: Surya-Raghuram [GitHub: Surya-Raghuram]

echo "Created by Surya-Raghuram [GitHub: Surya-Raghuram]"
echo ""

# don't let script run as root
if (( $EUID == 0 )); then
    echo -e "\n\nPlease DON'T run as root!\n"
    exit
fi

###############################################################################
# Removing proxies
###############################################################################

echo "Removing proxies from environment variables"
sudo sed -i '/http_proxy/d' /etc/environment
sudo sed -i '/https_proxy/d' /etc/environment
sudo sed -i '/ftp_proxy/d' /etc/environment
sudo sed -i '/socks_proxy/d' /etc/environment
sudo sed -i '/all_proxy/d' /etc/environment
sudo sed -i '/HTTP_PROXY/d' /etc/environment
sudo sed -i '/HTTPS_PROXY/d' /etc/environment
sudo sed -i '/FTP_PROXY/d' /etc/environment
sudo sed -i '/SOCKS_PROXY/d' /etc/environment
sudo sed -i '/ALL_PROXY/d' /etc/environment
sudo perl -i -pe 'chomp if eof' /etc/environment
echo "done."

echo "Removing proxies from pacman"
sudo sed -i '/XferCommand/d' /etc/pacman.conf
sudo sed -i '/ProxyServer/d' /etc/pacman.conf
sudo perl -i -pe 'chomp if eof' /etc/pacman.conf
echo "done."

echo "Removing proxies from yay"
rm -f ~/.config/yay/config.json
echo "done."

echo "Removing proxies from snap"
sudo snap set system proxy.http=
sudo snap set system proxy.https=
echo "done."

echo "Removing dconf proxy setting"
/usr/bin/gsettings set org.gnome.system.proxy mode 'none'
echo "done."

echo "Removing proxy settings from git"
git config --global --unset http.proxy
git config --global --unset https.proxy
echo "done."

echo "Removing proxy settings from npm"
npm config rm proxy
npm config rm https-proxy
echo "done."

###############################################################################
# Finish
###############################################################################

echo ""
echo "All done! Proxy settings successfully removed. If issues persist, log out/in or reboot."
